# Generated by Django 4.2.11 on 2026-05-20 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_projectimage_project_alter_brand_caption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Project title (e.g., 'Dettol Campaign')", max_length=200)),
                ('slug', models.SlugField(help_text='URL slug (auto-generated if not provided)', max_length=200, unique=True)),
                ('objective', models.TextField(help_text='Project objective and goals')),
                ('mechanisms', models.TextField(help_text='How the project was executed')),
                ('achievement', models.TextField(help_text='Results and achievements')),
                ('featured', models.BooleanField(default=False, help_text='Display on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameField(
            model_name='client',
            old_name='work_done',
            new_name='Execution',
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in gallery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.project')),
            ],
            options={
                'verbose_name': 'Project Image',
                'verbose_name_plural': 'Project Images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='brand',
            field=models.ForeignKey(help_text='Brand this project is associated with', on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.brand'),
        ),
    ]
