# Generated by Django 4.2.11 on 2026-05-20 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_project_rename_work_done_client_execution_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Execution',
            new_name='work_done',
        ),
    ]
